name: Build and Upload Python Package

on:
 release:
   types: [published]


permissions:
  contents: read
  id-token: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build wheels for selected dependencies
        run: |
          pip wheel -r requirements-build.txt -w dist

      - name: Build distribution
        run: |
          python -m build --sdist
          python -m build --wheel

      - name: Check distribution
        run: twine check dist/*
        
      - name: Set up .pypirc
        run: |
          cat <<EOF > ~/.pypirc
          [distutils]
            index-servers =
              pypi
              placekey
              testpypi

          [pypi]
            username = __token__
            password = ${{ secrets.PYPI_API_TOKEN }}

          [placekey]
            repository = https://upload.pypi.org/legacy/
            username = __token__
            password = ${{ secrets.PYPI_API_TOKEN }}

          [testpypi]
            repository = https://test.pypi.org/legacy/
            username = __token__
            password = ${{ secrets.TEST_PYPI_API_TOKEN }}
          EOF

      - name: Upload to TestPyPI
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN}}
        run: |
          twine upload --repository testpypi dist/*

      - name: Upload to PyPi
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN}}
        run: |
          twine upload pypi dist/*
